### ISSUE TITLE
stim issues

### ISSUE THREAD

**Issue by jvcasillas** [IvanAndreu/IStudy#6]
- la_salas_sergio.wav (added s, must be consistent between pilot stim and stim analysis projects)

**Comment by jvcasillas** [comment]
@IvanAndreu Pyschopy experiment is fixed now (woohoo!). Revisa los estimulos y avisame por aqui con lo que sea. Hago los cambios necesarios y actualizo el experimento... luego haces fork en pavlovia y pa'lante.

**Comment by IvanAndreuRascon** [comment]
Buenas el unico que he encontrado ha sido este  "la_salas_alejandro" (que fue el primero que hice)

**Comment by jvcasillas** [comment]
Ok. He actualizado el experimento en pavlovia. todo va bien. Si quieres jugar o problarlo pon "test" para el participant id. Si quieres puedes empezar a repartirlo entre amigos y tal. Usa esta version y haz lo del fork en otro momento. Eso s'i, si empiezas a recoger datos ya, haz una lista de quienes son los participantes y dales un id (tipo 'mono001', 'mono002', etc.). Intenta que sean monoling"ues (si son biling"es, que sean late learners del ingles). Lo voy vigilando y empiezo a escribir un script para analizar los datos. 👍🏼 

https://run.pavlovia.org/jvcasillas/s3_pilot
